### ISSUE TITLE
ACM - Create Bicycle Model of Car

### ISSUE THREAD

**Issue by BTyrrell01** [gopher-motorsports/aerodynamic-control-module#15]
To understand how changing the CP might affect cornering, make a generic bicycle model of the car.

**Comment by BTyrrell01** [comment]
After discussions with Ryan, bicycle model is likely not a good avenue for making aero design decisions. It is a much better platform for making CG decisions, and ride height, etc.

**Comment by hocally** [comment]
@BTyrrell01 There's always a [relevant TPB quote](https://twitter.com/TPBoysScreen/status/1361809923789750274?s=19)
