### ISSUE TITLE
ACM - Add readme file and update repo description

### ISSUE THREAD

**Issue by hocally** [gopher-motorsports/aerodynamic-control-module#4]
Use the [DLM](https://github.com/gopher-motorsports/data-logging-module/blob/main/README.md) as a template. The repo description can be edited from the main page. On the right there is a gear icon that allows you to edit the description.

**Comment by BTyrrell01** [comment]
I just added the README.md file with the information about this repo, however I am not an administrator of this repo and so I cannot change the description.
